name: AI News Trend Pipeline

on:
  schedule:
    - cron: '*/5 * * * *'  # Otomatis jalan setiap 3 menit
  workflow_dispatch:      # Tombol manual biar bisa dites kapan aja

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pipeline Script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python src/main_pipeline.py
